import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Cards from '@/components/Cards'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Power Up Those Skills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/powerful.svg"
            alt="Female raising her fist with a purple cape on to indicate she is empowered."
            width={618.6}
            height={423.3}
            priority
          />
        </div>

        <Cards />
      </main>
    </>
  )
}
