import Head from 'next/head'
import Navbar from '@/components/Navbar'
import styles from '@/styles/Home.module.css'

const Workshop = () => {
  return (
    <>
      <Head>
        <title>Power Up Those Skills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        
        <div className={styles.center}>
          {/* iframe options: w-800, h-450, w-1375 h-773.4375, w-1400 h-787.5 */}
          <iframe 
            className={styles.board} 
            width="1350" 
            height="759.375" 
            src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FOkkVgOZ2IobGwROxrzybTr%2FPower-Up-Those-Skills%253A-Gender-Diversity-in-Tech-Panel-Discussion-%252B-Workshop%3Fnode-id%3D6%253A1075%26t%3DqZ5UtwhGm84s4UGY-1" 
            allowfullscreen
          ></iframe>

          {/* BACK UP GOOGLE SLIDE DECK */}
          {/* <a
            href="https://docs.google.com/presentation/d/1UO5gXNMJ1rH1Wb-xBEvXowssg7vZLsmAwg75PDcp_wU/edit#slide=id.g20fbe4585f8_0_119"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.board}
          >
            <img
              src="/sticky-notes.png"
              alt="Reflection Notes"
              width={1126}
              height={639}
              priority
            />
          </a> */}

        </div>
      </main>
    </>
  );
}
 
export default Workshop;